# Generated by Django 3.0.2 on 2020-03-03 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_title', models.CharField(max_length=200)),
                ('obra_content', models.TextField()),
                ('obra_published', models.DateTimeField(verbose_name='date published')),
                ('obra_slug', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ObraFecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_fecha', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categoría',
            },
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_fecha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.ObraFecha', verbose_name='Fecha'),
        ),
    ]
